<?php

//Webserver Install Options from Gogetssl type 1
Configure::set("gogetsslv2.web_server_types.1", array (
    1 =>"AOL",
    2 =>"Apache / mod_ssl",
    3 =>"Apache-SSL (Ben-SSL, not Stronghold)",
    4 =>"C2Net Stronghold",
    5 =>"Cobalt Raq",
    6 =>"Covalent Server Software",
    7 =>"IBM HTTP Server",
    8 =>"IBM Internet Connection Server",
    9 =>"iPlanet",
    10 =>"Java Web Server (Javasoft Sun)",
    11 =>"Lotus Domino",
    12 =>"Lotus Domino Go!",
    13 =>"Microsoft IIS 1.x to 4.x",
    14 =>"Microsoft IIS 5.x to 6.x",
    15 =>"Netscape Enterprise Server",
    16 =>"Netscape FastTrack",
    17 =>"Novell Web Server",
    18 =>"Oracle",
    19 =>"Quid Pro Quo",
    20 =>"R3 SSL Server",
    21 =>"Raven SSL",
    22 =>"RedHat Linux",
    23 =>"SAP Web Application Server",
    24 =>"Tomcat",
    25 =>"Website Professional",
    26 =>"WebStar 4.x and later",
    27 =>"WebTen (from Tenon)",
    28 =>"Zeus Web Server",
    29 =>"Ensim",
    30 =>"Plesk",
    31 =>"WHM / cPanel",
    32 =>"H-Sphere",
    33 =>"Cisco 3000 Series VPN Concentrator",
    34 =>"Citrix",
    35 =>"Microsoft IIS 7.x and later",
    36 =>"Nginx",
    -1 =>"OTHER"
));
//Webserver Install Options from Gogetssl type
Configure::set("gogetsslv2.web_server_types.2", array (
    22  => "Apache + ApacheSSL",
    1   => "Apache + MOD SSL",
    20  => "Apache + OpenSSL",
    2   => "Apache + Raven",
    3   => "Apache + SSLeay",
    21  => "Apache 2",
    4   => "C2Net Stronghold",
    23  => "Cobalt Series",
    24  => "Cpanel",
    25  => "Ensim",
    26  => "Hsphere",
    7   => "IBM HTTP",
    8   => "iPlanet Server 4.1",
    27  => "Ipswitch",
    29  => "Jakart-Tomcat",
    11  => "Lotus Domino 4.6+",
    9   => "Lotus Domino Go 4.6.2.51",
    10  => "Lotus Domino Go 4.6.2.6+",
    12  => "Microsoft IIS 4.0",
    13  => "Microsoft IIS 7.x and later",
    33  => "Microsoft Internet Information Server",
    14  => "Netscape Enterprise/FastTrack",
    18  => "OTHER",
    31  => "O'Reilly WebSite Professional",
    28  => "Plesk",
    30  => "WebLogic – all versions",
    32  => "WebStar",
    17 => "Zeus v3+"
));
